language: node_js
node_js:
  - "7"
install:
  - npm install -g firebase-tools
script:
  - echo "Deployment in progress..."
after_success:
  - firebase deploy - project ow-stat-tracker-c6336 - token $FIREBASE_TOKEN.